### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by tobilg** [h0tbird/docker-volume-rbd#2]
If I try to run

```
docker run -it --volume-driver rbd -v foo:/foo alpine /bin/sh -c "echo -n 'hello ' > /foo/hw.txt"
```

I receive an

```
Error response from daemon: Plugin Error: {"Mountpoint":"","Err":"Unable to parse locker ID"}
```

error. I suspect that the current version of the Docker image is non-functional. If I try to execute `docker run -i  --rm --privileged --pid host --net host --volume /dev:/dev --volume /sys:/sys --volume /etc/ceph:/etc/ceph --volume /var/lib/ceph:/var/lib/ceph h0tbird/ceph:v9.2.0-2 rbd ls` for example, nothing happens. No error message at all, no success either.

Thanks for your help!

**Comment by h0tbird** [comment]
I have just fixed the `entrypoint` definition. Try this:

```
docker run -i --rm \
--privileged \
--pid host \
--net host \
--volume /dev:/dev \
--volume /sys:/sys \
--volume /etc/ceph:/etc/ceph \
--volume /var/lib/ceph:/var/lib/ceph \
--entrypoint rbd \
h0tbird/ceph:v9.2.0-2 ls -l
```

**Comment by tobilg** [comment]
Thanks for the fast feedback. Looks better now, but I still receive a keyring error:

```
2016-01-25 15:16:23.525577 7f9844ee47c0 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
2016-01-25 15:16:23.525590 7f9844ee47c0 -1 monclient(hunting): ERROR: missing keyring, cannot use cephx for authentication
2016-01-25 15:16:23.525592 7f9844ee47c0  0 librados: client.admin initialization error (2) No such file or directory
```

My keyring lives in `/var/lib/ceph/mon/ceph-coreos-hw-node-2/keyring` for example...

**Comment by tobilg** [comment]
Have a look at my PR https://github.com/ceph/ceph-docker/commit/31d239778982b024ba5cbd63458485eeb2ee5905

Probably this is too specific I guess. I'm using `etcd` as backend.

**Comment by h0tbird** [comment]
In my setup I expect the keyring in `/etc/ceph/` (ceph/ceph-docker#159):

```
core@core-8 ~ $ ll /etc/ceph/
total 32K
drwxr-xr-x  2 root root 4.0K Jan 23 05:44 ./
drwxr-xr-x 34 root root 4.0K Jan 25 15:26 ../
-rw-r--r--  1 root root  137 Jan 23 05:44 ceph.client.admin.keyring
-rw-r--r--  1 root root 1.8K Dec 28 09:25 ceph.conf
```

I am also using `etcd` as a KV store for my Ceph config.

**Comment by tobilg** [comment]
Hm, it doesn't get populated in my env...

**Comment by h0tbird** [comment]
Are you setting the environment variable (`--env CEPH_GET_ADMIN_KEY=1`) at container runtime?

**Comment by tobilg** [comment]
Is this somewhere documented at ceph/docker?

**Comment by h0tbird** [comment]
Hm, it is not :(

**Comment by tobilg** [comment]
Ok :-) Should one of us create a PR for the README.md of ceph/docker? I'll check tomorrow if it works... This needs to be used with the OSDs I guess, right?

**Comment by tobilg** [comment]
It works now, awesome! I added `--env CEPH_GET_ADMIN_KEY=1` to my OSD unit file, which triggers the creation of the keyring in `/etc/ceph`.
